# Generated by Django 2.1.1 on 2018-10-22 17:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='user name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('openid', models.CharField(default='', max_length=256, verbose_name='微信ID')),
                ('nickname', models.CharField(default='', max_length=256, verbose_name='昵称')),
                ('sex', models.IntegerField(default=1, verbose_name='性别')),
                ('province', models.CharField(default='', max_length=256, verbose_name='省')),
                ('country', models.CharField(default='中国', max_length=256, verbose_name='国')),
                ('headimgurl', models.CharField(default='http://thirdwx.qlogo.cn/mmopen/g3MonUZtNHkdmzicIlibx6iaFqAc56vxLSUfpb6n5WKSYVY0ChQKkiaJSgQ1dZuTOgvLLrhJbERQQ4eMsv84eavHiaiceqxibJxCfHe/46', max_length=1024, verbose_name='头像URL')),
                ('real_name', models.CharField(default='', max_length=256, verbose_name='真实姓名')),
                ('phone_number', models.CharField(default='', max_length=256, verbose_name='电话号码')),
                ('city', models.CharField(default='', max_length=256, verbose_name='城市')),
                ('address', models.CharField(default='', max_length=256, verbose_name='地址')),
                ('email_address', models.EmailField(default='', max_length=256, verbose_name='邮箱')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('user_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
    ]
