# Generated by Django 2.1.2 on 2019-02-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.CharField(default='', max_length=50, verbose_name='QQ'),
        ),
    ]
