# Generated by Django 2.1.2 on 2019-02-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_qq'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paycode',
            field=models.CharField(default='', max_length=50, verbose_name='支付密码'),
        ),
    ]
