# Generated by Django 2.0.7 on 2018-08-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180808_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='user name'),
        ),
    ]
