# Generated by Django 2.1.2 on 2019-02-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_paycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idback',
            field=models.ImageField(blank=True, null=True, upload_to='idcards', verbose_name='身份证反面'),
        ),
        migrations.AddField(
            model_name='user',
            name='idfront',
            field=models.ImageField(blank=True, null=True, upload_to='idcards', verbose_name='身份证正面'),
        ),
        migrations.AddField(
            model_name='user',
            name='idnum',
            field=models.CharField(default='', max_length=50, verbose_name='身份证号'),
        ),
    ]
