# Generated by Django 2.0.7 on 2018-09-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180821_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=256, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=256, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.EmailField(default='', max_length=256, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=256, verbose_name='电话号码'),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='', max_length=256, verbose_name='真实姓名'),
        ),
    ]
