# Generated by Django 2.1.2 on 2019-02-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180913_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idback',
            field=models.ImageField(blank=True, null=True, upload_to='idcards', verbose_name='身份证反面'),
        ),
        migrations.AddField(
            model_name='user',
            name='idfront',
            field=models.ImageField(blank=True, null=True, upload_to='idcards', verbose_name='身份证正面'),
        ),
        migrations.AddField(
            model_name='user',
            name='idnum',
            field=models.CharField(default='', max_length=50, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='user',
            name='paycode',
            field=models.CharField(default='', max_length=50, verbose_name='支付密码'),
        ),
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.CharField(default='', max_length=50, verbose_name='QQ'),
        ),
    ]
