# Generated by Django 2.1.2 on 2019-04-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_video_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='video_vip',
            field=models.IntegerField(choices=[(0, '非视频区VIP'), (1, '视频区VIP')], default=0, max_length=2, verbose_name='视频区会员'),
        ),
    ]
