# Generated by Django 2.0.7 on 2018-08-30 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfoLectureBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='广告名')),
                ('image', models.ImageField(upload_to='image', verbose_name='封面 1921×601 px')),
                ('url', models.CharField(db_index=True, max_length=256, verbose_name='图文栏目网址')),
            ],
            options={
                'verbose_name': 'b3免费视频讲座页面图片维护',
                'ordering': ['name'],
                'verbose_name_plural': 'b3免费视频讲座页面图片维护',
            },
        ),
        migrations.CreateModel(
            name='VideoInfoLectureComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256, verbose_name='视频评论')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='注册时间')),
                ('score', models.IntegerField(default=0, verbose_name='评论得分')),
                ('ascription', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='study.VideoInfoLecture', verbose_name='所属视频')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': 'bz免费视频讲座视频评论',
                'ordering': ['-register_date'],
                'verbose_name_plural': 'bz免费视频讲座视频评论',
            },
        ),
        migrations.CreateModel(
            name='VideoInfoStudyFuyangBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='广告名')),
                ('image', models.ImageField(upload_to='image', verbose_name='封面 1921×601 px')),
                ('url', models.CharField(db_index=True, max_length=256, verbose_name='图文栏目网址')),
            ],
            options={
                'verbose_name': 'b4天天乐页面图片维护',
                'ordering': ['name'],
                'verbose_name_plural': 'b4天天乐页面图片维护',
            },
        ),
        migrations.CreateModel(
            name='VideoInfoStudyFuyangComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256, verbose_name='视频评论')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='注册时间')),
                ('score', models.IntegerField(default=0, verbose_name='评论得分')),
                ('ascription', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='study.VideoInfoStudyFuyang', verbose_name='所属视频')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': 'bz免费视频讲座视频评论',
                'ordering': ['-register_date'],
                'verbose_name_plural': 'bz免费视频讲座视频评论',
            },
        ),
        migrations.AlterModelOptions(
            name='videoclass',
            options={'ordering': ['pub_date'], 'verbose_name': 'a2直播课程章节', 'verbose_name_plural': 'a2直播课程章节'},
        ),
        migrations.RemoveField(
            model_name='videoclass',
            name='index',
        ),
        migrations.RemoveField(
            model_name='videoinfo',
            name='url',
        ),
        migrations.AddField(
            model_name='videoclass',
            name='image',
            field=models.ImageField(null=True, upload_to='image', verbose_name='封面 480x270 px'),
        ),
        migrations.AddField(
            model_name='videoclass',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='play_app_id',
            field=models.CharField(blank=True, default='1257252657', max_length=256, null=True, verbose_name='录播视频appID'),
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='play_id',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='录播视频文件ID'),
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='price',
            field=models.IntegerField(default=0, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='users',
            field=models.ManyToManyField(editable=False, to=settings.AUTH_USER_MODEL, verbose_name='已购人员'),
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='image', verbose_name='封面 304x171 px'),
        ),
    ]
