# Generated by Django 2.0.7 on 2018-09-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20180831_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumtaskinfovideo',
            name='image_show_time',
            field=models.TextField(blank=True, default='', null=True, verbose_name='图片显示时间'),
        ),
        migrations.AddField(
            model_name='curriculumtaskinfovideo',
            name='live_image',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='当前直播显示的图片'),
        ),
    ]
