# Generated by Django 2.0.7 on 2018-09-11 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20180910_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklivefile',
            options={'ordering': ['-register_date'], 'verbose_name': 'a4直播章节资料', 'verbose_name_plural': 'a4直播章节资料'},
        ),
        migrations.RemoveField(
            model_name='videocurriculum',
            name='users',
        ),
        migrations.RemoveField(
            model_name='videoinfo',
            name='users',
        ),
        migrations.AddField(
            model_name='curriculumtaskinfovideo',
            name='speaking',
            field=models.BooleanField(default=True, verbose_name='是否可以发言'),
        ),
        migrations.AlterField(
            model_name='tasklivefile',
            name='ascription',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='study.VideoClass', verbose_name='所属章节'),
        ),
    ]
