# Generated by Django 2.0.7 on 2018-09-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20180911_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocurriculum',
            name='count',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
    ]
