# Generated by Django 2.0.7 on 2018-10-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_videocurriculum_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfolecture',
            name='sequeue',
            field=models.IntegerField(default=9999, verbose_name='排序'),
        ),
    ]
