# Generated by Django 2.0.7 on 2018-10-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_videoinfolecture_sequeue'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocurriculum',
            name='sequeue',
            field=models.IntegerField(default=9999, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='videoinfostudyfuyang',
            name='sequeue',
            field=models.IntegerField(default=9999, verbose_name='排序'),
        ),
    ]
