# Generated by Django 2.0.7 on 2018-10-03 00:02

import DjangoUeditor.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_auto_20181002_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='标题')),
                ('introduce', models.TextField(default='', verbose_name='简介')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='正文')),
                ('image', models.ImageField(upload_to='image', verbose_name='封面')),
                ('file', models.FileField(upload_to='files/', verbose_name='文件')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='更新日期')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '资料区',
                'verbose_name': '资料区',
                'db_table': 'datalist',
            },
        ),
        migrations.CreateModel(
            name='SinglePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='正文')),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='更新日期')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '单页面维护',
                'verbose_name': '单页面维护',
                'db_table': 'singlepage',
            },
        ),
    ]
