# Generated by Django 2.0.7 on 2018-10-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_datalst_singlepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvertisingBanners',
        ),
        migrations.DeleteModel(
            name='VideoInfoLectureBanners',
        ),
        migrations.DeleteModel(
            name='VideoInfoStudyFuyangBanners',
        ),
    ]
