# Generated by Django 2.0.7 on 2018-10-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_auto_20181003_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocurriculum',
            name='views_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='浏览次数'),
        ),
    ]
