# Generated by Django 2.0.7 on 2018-10-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0011_videocurriculum_views_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mianinfo',
            options={'verbose_name': '顶部背景图片设置', 'verbose_name_plural': '顶部背景图片设置'},
        ),
        migrations.AlterModelOptions(
            name='videoinfolecture',
            options={'ordering': ['name'], 'verbose_name': '视频区', 'verbose_name_plural': '视频区'},
        ),
        migrations.AlterModelOptions(
            name='videoinfolecturecomment',
            options={'ordering': ['-register_date'], 'verbose_name': '视频区评论', 'verbose_name_plural': '视频区评论'},
        ),
        migrations.AddField(
            model_name='mianinfo',
            name='background',
            field=models.ImageField(default='image/title_bg.png', upload_to='image', verbose_name='背景图片'),
        ),
        migrations.AlterField(
            model_name='mianinfo',
            name='text_1',
            field=models.CharField(max_length=256, verbose_name='Alt文字'),
        ),
        migrations.AlterField(
            model_name='mianinfo',
            name='text_2',
            field=models.CharField(max_length=256, verbose_name='LongDesc文字'),
        ),
    ]
