# Generated by Django 2.1.2 on 2018-11-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0012_auto_20181022_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mianinfo',
            options={'verbose_name': '站点信息配置', 'verbose_name_plural': '站点信息配置'},
        ),
        migrations.AlterModelOptions(
            name='taskinfovideocomment',
            options={'ordering': ['-register_date'], 'verbose_name': 'a7直播评论', 'verbose_name_plural': 'a7直播评论'},
        ),
        migrations.AddField(
            model_name='mianinfo',
            name='name',
            field=models.CharField(default='扶阳医学', max_length=256, verbose_name='站点名称'),
        ),
        migrations.AddField(
            model_name='mianinfo',
            name='wordsclean',
            field=models.TextField(blank=True, max_length=256, verbose_name='评论内容过虑'),
        ),
        migrations.AlterField(
            model_name='mianinfo',
            name='text_1',
            field=models.CharField(max_length=256, verbose_name='站点关键字'),
        ),
        migrations.AlterField(
            model_name='mianinfo',
            name='text_2',
            field=models.CharField(max_length=256, verbose_name='站点描述'),
        ),
    ]
