# Generated by Django 2.1.2 on 2018-12-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0013_auto_20181105_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mianinfo',
            name='wordsclean',
            field=models.TextField(blank=True, help_text='使用,|;分隔', max_length=256, verbose_name='评论内容过虑'),
        ),
    ]
