# Generated by Django 2.1.2 on 2019-04-01 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0016_auto_20190317_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoinfolectureclassfy',
            options={'ordering': ['register_date'], 'verbose_name': '视频区一级分类表', 'verbose_name_plural': '视频区一级分类表'},
        ),
        migrations.AddField(
            model_name='videoinfolectureclassfy',
            name='sequeue',
            field=models.IntegerField(default=9999, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='videoinfolecture',
            name='lecture_type_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vlist', to='study.VideoInfoLectureClassfy', verbose_name='视频一级分类'),
        ),
    ]
