# Generated by Django 2.1.2 on 2019-04-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0017_auto_20190401_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoinfolecture',
            options={'ordering': ['sequeue'], 'verbose_name': '视频区', 'verbose_name_plural': '视频区'},
        ),
    ]
