# Generated by Django 2.1.2 on 2019-04-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0018_auto_20190407_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoVipPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIP_price', models.IntegerField(default=9999, verbose_name='VIP价格')),
            ],
            options={
                'verbose_name': '视频区VIP会员价格表',
                'verbose_name_plural': '视频区VIP会员价格表',
                'ordering': ['VIP_price'],
            },
        ),
        migrations.AddField(
            model_name='videoinfolecture',
            name='viede_set_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='视频选集名称'),
        ),
        migrations.AddField(
            model_name='videoinfolecture',
            name='viede_set_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='视频选集顺序'),
        ),
        migrations.AddField(
            model_name='videoinfolectureclassfy',
            name='show_type',
            field=models.CharField(choices=[(0, '一行两列'), (1, '一行三列')], default=0, max_length=2, verbose_name='显示方式'),
        ),
        migrations.AlterField(
            model_name='videoinfolecture',
            name='lecture_type_second',
            field=models.CharField(choices=[('0', '最新课程'), ('1', '全部课程'), ('2', '名师课程')], default='0', max_length=2, verbose_name='视频二级分类'),
        ),
    ]
