# Generated by Django 2.1.2 on 2019-04-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0019_auto_20190407_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfolecture',
            name='lecture_type_second',
            field=models.CharField(choices=[('0', '最新课程'), ('1', '全部课程')], default='0', max_length=2, verbose_name='视频二级分类'),
        ),
    ]
