# Generated by Django 2.2 on 2019-04-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0024_auto_20190421_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfolecturedetails',
            name='sequence',
            field=models.IntegerField(default=1, verbose_name='第几集'),
        ),
    ]
