# Generated by Django 2.2 on 2019-04-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0025_videoinfolecturedetails_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfolecture',
            name='lecture_type_second',
            field=models.CharField(choices=[('0', '最新'), ('1', '全部')], default='0', max_length=2, verbose_name='视频二级分类'),
        ),
        migrations.AlterField(
            model_name='videoinfolecture',
            name='pay_type',
            field=models.CharField(choices=[('0', '免费'), ('1', '余额/微信'), ('2', '听课券'), ('3', 'VIP')], default='0', max_length=2, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='videoinfolecturedetails',
            name='pay_type',
            field=models.CharField(choices=[('0', '免费'), ('1', '余额/微信'), ('2', '听课券'), ('3', 'VIP')], default='0', max_length=2, verbose_name='支付方式'),
        ),
    ]
