# Generated by Django 2.1.1 on 2018-10-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='广告名')),
                ('image', models.ImageField(upload_to='image', verbose_name='封面 1921×601 px')),
                ('url', models.CharField(db_index=True, max_length=256, verbose_name='图文栏目网址')),
            ],
            options={
                'verbose_name': 'z2课程报名页面图片维护',
                'verbose_name_plural': 'z2课程报名页面图片维护',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoInfoLectureBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='广告名')),
                ('image', models.ImageField(upload_to='image', verbose_name='封面 1921×601 px')),
                ('url', models.CharField(db_index=True, max_length=256, verbose_name='图文栏目网址')),
            ],
            options={
                'verbose_name': 'b3免费视频讲座页面图片维护',
                'verbose_name_plural': 'b3免费视频讲座页面图片维护',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoInfoStudyFuyangBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='广告名')),
                ('image', models.ImageField(upload_to='image', verbose_name='封面 1921×601 px')),
                ('url', models.CharField(db_index=True, max_length=256, verbose_name='图文栏目网址')),
            ],
            options={
                'verbose_name': 'b4天天乐页面图片维护',
                'verbose_name_plural': 'b4天天乐页面图片维护',
                'ordering': ['name'],
            },
        ),
    ]
