# Generated by Django 2.1.2 on 2019-04-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_auto_20181003_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAlternateBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='广告名')),
                ('image', models.ImageField(upload_to='image', verbose_name='封面 2:1 ')),
                ('url', models.CharField(db_index=True, max_length=256, verbose_name='图文栏目网址')),
                ('sequence', models.IntegerField(default=9999, verbose_name='排序')),
            ],
            options={
                'verbose_name': '视频区滚动页面广告维护',
                'verbose_name_plural': '视频区滚动页面广告维护',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='VideoInnerAdBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='广告名')),
                ('image', models.ImageField(upload_to='image', verbose_name='封面 2:1 ')),
                ('url', models.CharField(db_index=True, max_length=256, verbose_name='图文栏目网址')),
                ('sequence', models.IntegerField(default=9999, verbose_name='排序')),
            ],
            options={
                'verbose_name': '视频首页内部广告图片维护',
                'verbose_name_plural': '视频首页内部广告图片维护',
                'ordering': ['sequence'],
            },
        ),
    ]
