# Generated by Django 2.0.7 on 2018-10-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocurriculumorder',
            name='ticket',
            field=models.CharField(default='咨询费', max_length=255, verbose_name='发票内容'),
        ),
    ]
