# Generated by Django 2.1.2 on 2019-04-08 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_videocurriculumorder_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoinfolectureorder',
            options={'ordering': ['-register_date'], 'verbose_name': 'o1视频订单', 'verbose_name_plural': 'o1视频订单'},
        ),
        migrations.AlterField(
            model_name='videoinfolectureorder',
            name='video',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='study.VideoInfoLecture', verbose_name='视频讲座'),
        ),
    ]
