# Generated by Django 2.1.2 on 2018-12-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictureText', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picturetextpaper',
            name='video',
        ),
        migrations.AddField(
            model_name='picturetextpaper',
            name='price',
            field=models.IntegerField(default=0, verbose_name='价格'),
        ),
    ]
