# Generated by Django 2.0.7 on 2018-10-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictureText', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturetextcolumn',
            name='category',
            field=models.CharField(default='', max_length=50, verbose_name='所属类别'),
        ),
    ]
