# Generated by Django 2.0.7 on 2018-10-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictureText', '0002_picturetextcolumn_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturetextpaper',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='picturetextpapercomment',
            name='message',
            field=models.TextField(max_length=256, verbose_name='图文评论'),
        ),
    ]
