# Generated by Django 2.1.2 on 2018-12-02 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0014_auto_20181202_2243'),
        ('PictureText', '0003_auto_20181018_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturetextpaper',
            name='video',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='study.VideoCurriculum', verbose_name='所属课程'),
            preserve_default=False,
        ),
    ]
